config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :tags, only: [:show]
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader

    has_many :taggings
    has_many :tags, through: :taggings

    validates :title, :summary, :body, presence: true
    def all_tags
        self.tags.map(&:name).join(', ')
    end

    def all_tags=(names)
        self.tags = names.split(',').map do |name|
            Tag.where(name: name.strip).first_or_create!
    end
end
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :taggings
    has_many :posts, through: :taggings


def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :danger, :info, :warning
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [ :show, :edit, :update, :destroy]

    def index
        @posts = Post.all
    end

    def show
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save 
            redirect_to @post, success: 'Post successully created'
        else
            render :new, danger: 'Post isn`t saved'
        end
    end

    def edit
        
    end

    def update
        
        if @post.update(post_params)
            redirect_to @post, success: 'Post successully updated'
        else
            render :edit, danger: 'Post isn`t updated'
        end

    end

    def destroy
        @post.destroy
        redirect_to posts_path, success: 'Post successully deleted'
    end

    private
    def set_post
        @post = Post.find(params[:id])
    end
    def post_params
        params.require(:post).permit(:title, :summary, :body, :image, :all_tags)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find_by(name: params[:id])
        @posts = @tag.posts
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def tag_cloud(tags, classes)
        max = tags.sort_by(&:count).last 
        tags.each do |tag|
            index = tag.count.to_f / max.count * (classes.size-1)
            yield(tag, classes[index.round])
    end
end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Logo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= posts_path%>">Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contacts</a>
          </li>
          
        </ul>
        
      </div>
      <%= link_to 'New post', new_post_path, class: 'btn btn-outline-primary pull-xs-right'%>
    </div>
  </nav>
  </div>

  <div class="container main">
    <div class="row">
      <div class="col-md-12">
      <% flash.each do |name, message|%>
        <div class="alert alert-<%= name%>">
          <%= message %>
        </div>
        <% end %>
      </div>
    </div>

  <div class="row">
      <div class="col-md-8">
       <%= yield %>
      </div>
      <div class="col-md-4">
      <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class|%>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
      </div>
  </div>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any?%>
    <div class="alert alert-danger">
        <h5><%= t('common.errors')%></h5>
            <ul>
                <%= @post.errors.full_messages.each do |message| %>
                    <li><%= message%> </li>
                    <% end %>
            </ul>
    </div>
<% end %>
<%= form_for @post, html: {multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary, class: 'form-control' %>
    </div>

    <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, class: 'form-control bodyEdit' %>
    </div>
    <div class="form-group">
     <%= f.label :all_tags %>
     <%= f.text_field :all_tags, class: 'form-control' %>
    </div>
    <p></p>
    <div class="form-group">
     <%= f.file_field :image %>
    </div>
    <p></p>
    <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Back', :back, class: 'btn btn-outline-secondary'%>
    </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
    <section class="post-head">
        <h2><%= link_to post.title, post_path(post) %></h2>
        <small>
            <time><%= post.created_at.to_date.strftime("%d %B, %Y")%></time>
            |
            <%= link_to 'Edit', edit_post_path(post) %>
            |
            <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: "Are you sure?"} %>
        </small>
    </section>

    <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image?%>
    <%= post.summary %>
    </section>
    <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary' }.join(' ')%>
    <%= post.summary %>
    </section>
</article>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render @posts %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
    <section class="post-head">
        <h1><%=@post.title %></h1>
        <small>
            <time><%= @post.created_at.to_date.strftime("%d %B, %Y")%></time>
            |
            <%= link_to 'Edit', edit_post_path(@post) %>
            |
            <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
        </small>
    </section>

    <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image?%>
    <%= @post.body %>
    </section>
</article>

app/views/tags/show.html.erb
<h1><%= @tag.name%></h1>
<% if @tag.posts.empty? %>
<h2>No posts</h2>
<% else %>
    <%= render @tag.posts %>
    <% end %>